using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Utilities;

namespace ED.DOTS.EntitiesRequests.SourceGeneratorNew
{
    /// <summary>
    /// Incremental source generator for the new requests core (namespace <c>ED.DOTS.EntitiesRequests.Tmp</c>).
    /// For every type registered with <c>[assembly: RegisterRequest(typeof(T))]</c> it emits the closed
    /// generic component registration and a request system into the very assembly that declared the attribute.
    /// </summary>
    [Generator]
    public sealed class SourceGeneratorNew : IIncrementalGenerator
    {
        /// <summary>Metadata name of the registration attribute of the new core.</summary>
        private const string RegistrationAttributeMetadataName = "ED.DOTS.EntitiesRequests.Tmp.RegisterRequestAttribute";

        /// <summary>Suffix of the generated per-type request system.</summary>
        private const string SystemSuffix = "_RequestSystem";

        private readonly FileLogger _logger = new FileLogger("EntitiesRequestsNEW");

        /// <summary>Builds the incremental pipeline: assembly attributes to request models to sources.</summary>
        /// <param name="context">Incremental generator context.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var requests = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    RegistrationAttributeMetadataName,
                    IsCompilationUnit,
                    CollectRequests)
                .SelectMany(FlattenModels);

            context.RegisterSourceOutput(requests, Emit);
        }

        private static bool IsCompilationUnit(SyntaxNode node, CancellationToken cancellationToken)
        {
            return node is CompilationUnitSyntax;
        }

        private static ImmutableArray<RequestModel> FlattenModels(ImmutableArray<RequestModel> models, CancellationToken cancellationToken)
        {
            return models;
        }

        private ImmutableArray<RequestModel> CollectRequests(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
        {
            var builder = ImmutableArray.CreateBuilder<RequestModel>();
            for (var i = 0; i < context.Attributes.Length; i++)
            {
                var typeSymbol = ReadRequestType(context.Attributes[i]);
                if (typeSymbol == null)
                {
                    continue;
                }

                if (typeSymbol.ContainingType != null)
                {
                    _logger.Error($"{nameof(SourceGeneratorNew)}: nested request types are not supported: {typeSymbol.ToDisplayString()}.");
                    continue;
                }

                builder.Add(RequestModel.Create(typeSymbol));
            }

            return builder.ToImmutable();
        }

        private INamedTypeSymbol ReadRequestType(AttributeData attribute)
        {
            if (attribute.ConstructorArguments.Length != 1)
            {
                _logger.Error($"{nameof(SourceGeneratorNew)}: RegisterRequest expects exactly one argument.");
                return null;
            }

            var argument = attribute.ConstructorArguments[0];
            if (argument.Kind == TypedConstantKind.Error)
            {
                _logger.Error($"{nameof(SourceGeneratorNew)}: RegisterRequest argument failed to bind to a type.");
                return null;
            }

            var typeSymbol = argument.Value as INamedTypeSymbol;
            if (typeSymbol == null)
            {
                _logger.Error($"{nameof(SourceGeneratorNew)}: RegisterRequest argument is not a named type.");
                return null;
            }

            return typeSymbol;
        }

        private void Emit(SourceProductionContext context, RequestModel model)
        {
            var hintName = $"NEW_{model.Name}{SystemSuffix}.g.cs";
            var sourceCode = GenerateCode(model);
            context.AddSource(hintName, SourceText.From(sourceCode, Encoding.UTF8));
            _logger.Info($"{nameof(SourceGeneratorNew)}: generated {hintName} for {model.FullName}.");
        }

        private static string GenerateCode(RequestModel model)
        {
            var systemName = model.Name + SystemSuffix;
            var hasNamespace = !string.IsNullOrWhiteSpace(model.Namespace);
            var indent = hasNamespace ? "    " : string.Empty;

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("using Unity.Burst;");
            builder.AppendLine("using Unity.Entities;");
            builder.AppendLine("using ED.DOTS.EntitiesRequests.Tmp;");
            builder.AppendLine();
            builder.AppendLine($"[assembly: RegisterGenericComponentType(typeof(RequestSingleton<{model.FullName}>))]");
            builder.AppendLine();

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {model.Namespace}");
                builder.AppendLine("{");
            }

            builder.AppendLine($"{indent}[UpdateInGroup(typeof(RequestSystemGroup))]");
            builder.AppendLine($"{indent}[WorldSystemFilter(WorldSystemFilterFlags.ClientSimulation");
            builder.AppendLine($"{indent}                   | WorldSystemFilterFlags.ServerSimulation");
            builder.AppendLine($"{indent}                   | WorldSystemFilterFlags.LocalSimulation)]");
            builder.AppendLine($"{indent}[BurstCompile]");
            builder.AppendLine($"{indent}public partial struct {systemName} : ISystem");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    [BurstCompile]");
            builder.AppendLine($"{indent}    public void OnCreate(ref SystemState state)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        RequestOwner<{model.FullName}>.OnCreate(ref state);");
            builder.AppendLine($"{indent}    }}");
            builder.AppendLine();
            builder.AppendLine($"{indent}    [BurstCompile]");
            builder.AppendLine($"{indent}    public void OnUpdate(ref SystemState state)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        RequestOwner<{model.FullName}>.OnUpdate(ref state);");
            builder.AppendLine($"{indent}    }}");
            builder.AppendLine();
            builder.AppendLine($"{indent}    [BurstCompile]");
            builder.AppendLine($"{indent}    public void OnDestroy(ref SystemState state)");
            builder.AppendLine($"{indent}    {{");
            builder.AppendLine($"{indent}        RequestOwner<{model.FullName}>.OnDestroy(ref state);");
            builder.AppendLine($"{indent}    }}");
            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }
    }
}
