using System;
using Microsoft.CodeAnalysis;
using Utilities;

namespace ED.DOTS.EntitiesRequests.SourceGenerator
{
    [Generator]
    public class SourceGenerator : ISourceGenerator
    {
        private FileLogger Logger { get; } = new FileLogger("EntitiesRequests");

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var helper = new CodeBuildHelper(context.Compilation);
            var assemblyAttributes = context.Compilation.Assembly.GetAttributes();

            foreach (var attribute in assemblyAttributes)
            {
                try
                {
                    if (!helper.IsRegistrationAttribute(attribute))
                        continue;

                    if (attribute.ConstructorArguments.Length != 1)
                    {
                        Logger.Error($"{GetType().Name}: Attribute arguments length is not 1.");
                        continue;
                    }

                    var ctorArg = attribute.ConstructorArguments[0];
                    if (!(ctorArg.Value is INamedTypeSymbol typeSymbol))
                    {
                        Logger.Error($"{GetType().Name}: Attribute argument is not a type symbol.");
                        continue;
                    }

                    var requestTypeName = typeSymbol.Name;
                    var requestTypeNamespace = typeSymbol.ContainingNamespace?.ToString();

                    GenerateCode(requestTypeName, requestTypeNamespace, out var fileName, out var sourceCode);
                    context.AddSource(fileName, sourceCode);
                    Logger.Info($"{GetType().Name}: Generated source {fileName}");
                }
                catch (Exception e)
                {
                    Logger.Error(e.ToString());
                }
            }
        }

        private static void GenerateCode(string requestTypeName, string requestTypeNamespace, out string fileName, out string sourceCode)
        {
            var fullTypeName = string.IsNullOrWhiteSpace(requestTypeNamespace) ? requestTypeName : $"{requestTypeNamespace}.{requestTypeName}";
            fileName = $"{requestTypeName}_RequestSystem.g.cs";

            sourceCode = $@"// <auto-generated/>
using Unity.Entities;
using ED.DOTS.EntitiesRequests;

[assembly: RegisterGenericComponentType(typeof(RequestSingleton<{fullTypeName}>))]

{(string.IsNullOrWhiteSpace(requestTypeNamespace) ? "" : $@"namespace {requestTypeNamespace}
{{")}
    partial class {requestTypeName}_RequestSystem : RequestSystemBase<{fullTypeName}> {{ }}
{(string.IsNullOrWhiteSpace(requestTypeNamespace) ? "" : $@"
}}")}
";
        }
    }
}