using System;
using Microsoft.CodeAnalysis;

namespace EntitiesRequestsSourceGenerator
{
    [Generator]
    public class SourceGenerator : ISourceGenerator
    {
        private FileLogger Logger { get; } = new FileLogger();

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            foreach (AttributeData attribute in context.Compilation.Assembly.GetAttributes())
            {
                try
                {
                    if (!CodeBuildHelper.IsRegistrationAttribute(attribute)) continue;
                    
                    if (attribute.ConstructorArguments.Length != 1)
                    {
                        Logger.Error($"{GetType().Name}: Attribute arguments length is not 1.");
                        continue;
                    }
                    
                    var ctorArg = attribute.ConstructorArguments[0];
                    var typeSymbol = ctorArg.Value as INamedTypeSymbol;
                    var name = typeSymbol?.Name;

                    if (name == null)
                    {
                        Logger.Error($"{GetType().Name}: The type of parameter has no name.");
                        continue;
                    }

                    var @namespace = typeSymbol?.ContainingNamespace?.Name;

                    GenerateCode(name, @namespace, out var file, out var code);
                    context.AddSource(file, code);
                    Logger.Info($"{GetType().Name}: Generated source {file}");
                }
                catch (Exception e)
                {
                    Logger.Error(e.ToString());
                }
            }
        }

        private static void GenerateCode(string name, string @namespace, out string file, out string code)
        {
            var fullname = string.IsNullOrWhiteSpace(@namespace) ? name : $"{@namespace}.{name}";

            file = $"{name}_RequestSystem.cs";
            code = $@"// This code was generated by the EntitiesRequestsSourceGenerator.

using Unity.Entities;
using ED.DOTS.EntitiesRequests;
using ED.DOTS.EntitiesRequests.Internal;

[assembly: RegisterGenericComponentType(typeof(RequestSingleton<{fullname}>))]

{(string.IsNullOrWhiteSpace(@namespace) ? "" : $@"namespace {@namespace}
{{")}
    partial class {name}_RequestSystem : EventSystemBase<{fullname}> {{ }}
{(string.IsNullOrWhiteSpace(@namespace) ? "" : $@"
}}")}
";
        }
    }
}